# -*- coding: utf-8 -*-
#
#  helpers/radius.py
#
# Copyright 2021 Filippo Maria LAURIA <filippo.lauria@iit.cnr.it>
#
# Institute of Informatics and Telematics (IIT)
# Italian National Council of Research (CNR)
#
#
# This file is part of the Minimal FreeRADIUS GUI (MFG).
#
# The Minimal FreeRADIUS GUI (MFG) is free software: you can redistribute
# it and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# The Minimal FreeRADIUS GUI (MFG) is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Minimal FreeRADIUS GUI (MFG).
# If not, see <http://www.gnu.org/licenses/>.
#

# allowed operators in tables radcheck, radreply, radgroupcheck, radgroupreply
operators = ['=', ':=', '==', '+=', '!=', '>', '>=', '<', '<=', '=~', '!~', '=*', '!*']

# standard dictionary of radius attributes
attributes = ['ARAP-Challenge-Response',
              'ARAP-Features',
              'ARAP-Password',
              'ARAP-Security',
              'ARAP-Security-Data',
              'ARAP-Zone-Access',
              'AUTH-Key',
              'Access-Accept',
              'Access-Challenge',
              'Access-Reject',
              'Access-Request',
              'Accounting-Request',
              'Accounting-Response',
              'Acct-Authentic',
              'Acct-Delay-Time',
              'Acct-Input-Gigawords',
              'Acct-Input-Octets',
              'Acct-Input-Packets',
              'Acct-Interim-Interval',
              'Acct-Link-Count',
              'Acct-Multi-Session-Id',
              'Acct-Output-Gigawords',
              'Acct-Output-Octets',
              'Acct-Output-Packets',
              'Acct-Session-Id',
              'Acct-Session-Time',
              'Acct-Status-Type',
              'Acct-Terminate-Cause',
              'Acct-Tunnel-Connection',
              'Acct-Tunnel-Packets-Lost',
              'CHAP-Challenge',
              'CHAP-Password',
              'Callback-Id',
              'Callback-Number',
              'Called-Station-Id',
              'Calling-Station-Id',
              'Change-of-Authorization',
              'Chargeable-User-Identity',
              'Class',
              'Configuration-Token',
              'Connect-Info',
              'DNS-Server-IPv6-Address',
              'DS-Lite',
              'DS-Lite-Tunnel-Name',
              'Delegated-IPv6-Prefix',
              'Delegated-IPv6-Prefix-Pool',
              'Digest-AKA-Auts',
              'Digest-Algorithm',
              'Digest-Auth-Param',
              'Digest-CNonce',
              'Digest-Domain',
              'Digest-Entity-Body-Hash',
              'Digest-HA1',
              'Digest-Method',
              'Digest-Nextnonce',
              'Digest-Nonce',
              'Digest-Nonce-Count',
              'Digest-Opaque',
              'Digest-Qop',
              'Digest-Realm',
              'Digest-Response',
              'Digest-Response-Auth',
              'Digest-Stale',
              'Digest-URI',
              'Digest-Username',
              'EAP-Message',
              'Error-Cause',
              'Event-Timestamp',
              'Extended-Type-1',
              'Extended-Type-2',
              'Extended-Type-3',
              'Extended-Type-4',
              'Extended-Vendor-Specific-1',
              'Extended-Vendor-Specific-2',
              'Extended-Vendor-Specific-3',
              'Extended-Vendor-Specific-4',
              'Extended-Vendor-Specific-5',
              'Extended-Vendor-Specific-6',
              'Filter-ID',
              'Filter-Id',
              'Framed-AppleTalk-Link',
              'Framed-AppleTalk-Network',
              'Framed-AppleTalk-Zone',
              'Framed-Compression',
              'Framed-IP-Address',
              'Framed-IP-Netmask',
              'Framed-IPX-Network',
              'Framed-IPv6-Address',
              'Framed-IPv6-Pool',
              'Framed-IPv6-Prefix',
              'Framed-IPv6-Route',
              'Framed-Interface-Id',
              'Framed-MTU',
              'Framed-Management-Protocol',
              'Framed-Pool',
              'Framed-Protocol',
              'Framed-Route',
              'Framed-Routing',
              'Idle-Timeout',
              'Keep-Alives',
              'Login-IP-Host',
              'Login-IPv6-Host',
              'Login-LAT-Group',
              'Login-LAT-Node',
              'Login-LAT-Port',
              'Login-LAT-Service',
              'Login-Service',
              'Login-TCP-Port',
              'Long-Extended-Type-1',
              'Long-Extended-Type-2',
              'MS-ARAP-Challenge',
              'MS-ARAP-Password-Change-Reason',
              'MS-Acct-Auth-Type',
              'MS-Acct-EAP-Type',
              'MS-BAP-Usage',
              'MS-CHAP-CPW-1',
              'MS-CHAP-CPW-2',
              'MS-CHAP-Challenge',
              'MS-CHAP-Domain',
              'MS-CHAP-Error',
              'MS-CHAP-LM-Enc-PW',
              'MS-CHAP-MPPE-Keys',
              'MS-CHAP-NT-Enc-PW',
              'MS-CHAP-Response',
              'MS-CHAP2-CPW',
              'MS-CHAP2-Response',
              'MS-CHAP2-Success',
              'MS-Filter',
              'MS-Link-Drop-Time-Limit',
              'MS-Link-Utilization-Threshold',
              'MS-MPPE-Encryption-Policy',
              'MS-MPPE-Encryption-Types',
              'MS-MPPE-Recv-Key',
              'MS-MPPE-Send-Key',
              'MS-New-ARAP-Password',
              'MS-Old-ARAP-Password',
              'MS-Primary-DNS-Server',
              'MS-Primary-NBNS-Server',
              'MS-RAS-Vendor',
              'MS-RAS-Version',
              'MS-Secondary-DNS-Server',
              'MS-Secondary-NBNS-Server',
              'Management-Policy-Id',
              'Management-Privilege-Level',
              'Management-Transport-Protection',
              'Message-Authenticator',
              'Mobile-Node-Identifier',
              'NAS-Filter-Rule',
              'NAS-IP-Address',
              'NAS-IPv6-Address',
              'NAS-Identifier',
              'NAS-Port',
              'NAS-Port-Id',
              'NAS-Port-Type',
              'PKM-AUTH-Key',
              'PKM-CA-Cert',
              'PKM-Config-Settings',
              'PKM-Cryptosuite-List',
              'PKM-SA-Descriptor',
              'PKM-SAID',
              'PKM-SS-Cert',
              'Password-Retry',
              'Port-Limit',
              'Proxy-State',
              'Reply-Message',
              'Route-IPv6-Information',
              'SIP-AOR',
              'Service-Selection',
              'Service-Type',
              'Session-Timeout',
              'State',
              'Stateful-IPv6-Address-Pool',
              'Termination-Action',
              'Tunnel-Assignment-ID',
              'Tunnel-Client-Auth-ID',
              'Tunnel-Client-Endpoint',
              'Tunnel-Link-Reject',
              'Tunnel-Link-Start',
              'Tunnel-Link-Stop',
              'Tunnel-Medium-Type',
              'Tunnel-Password',
              'Tunnel-Preference',
              'Tunnel-Private-Group-ID',
              'Tunnel-Reject',
              'Tunnel-Server-Auth-ID',
              'Tunnel-Server-Endpoint',
              'Tunnel-Start',
              'Tunnel-Stop',
              'Tunnel-Type',
              'User-Name',
              'User-Password',
              'Vendor-Id',
              'Vendor-Specific']
